# Generated by Django 5.0.6 on 2024-08-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_nivel_riesgo', models.CharField(max_length=50)),
                ('id_tipo_nivel_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.tiponivelriesgo')),
            ],
        ),
    ]
