# Generated by Django 5.0.6 on 2024-08-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descp_cargo', models.CharField(max_length=50)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_nivel_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.nivelriesgo')),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
    ]
