# Generated by Django 5.0.6 on 2024-08-06 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleado'),
        ('empresa', '0004_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_documento', models.CharField(max_length=20)),
                ('fecha_vinculacion', models.DateField()),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cargo')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('id_tipo_vinculacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.tipovinculacion')),
            ],
        ),
    ]
