# Generated by Django 5.0.6 on 2024-08-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nro_documento', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('estado_sistema', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.rol')),
            ],
        ),
    ]
