# Generated by Django 5.0.6 on 2024-08-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_tipodocumento_alter_empleado_estado_sistema_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
